version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: recam-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    ports:
      - "${SQL_SERVER_PORT:-1433}:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    restart: unless-stopped

  mongodb:
    image: mongo:7
    container_name: recam-mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - mongodb-data:/data/db
    restart: unless-stopped

volumes:
  sqlserver-data:
  mongodb-data:
